/**
 * SPLIT-197 §C-MCP — the MCP tool layer's typed view of the backend contract.
 *
 * Every type here is derived from `src/generated/api-types.gen.ts`, itself
 * generated by `npm run gen:api` (openapi-typescript) from the backend's
 * committed `openapi/openapi.json`. This replaces the tool layer's hand-rolled
 * `BackendBooking` / `ConversationRecord` / inline response interfaces so the
 * tools are type-checked against the real API contract and stop drifting
 * silently — the SPLIT-197 goal.
 *
 * There are two derivation styles, chosen by what the spec actually declares:
 *
 *  1. `GetResponse<P>` / `PostResponse<P>` extract the 200/201 `application/json`
 *     body a path binds in the contract — mirroring the frontend's
 *     `utils/apiClient.ts` path-derivation. Used where the backend controller
 *     declares a real typed response (POST /bookings → `Booking`,
 *     GET /bookings/{id} → `BookingResponseDto`,
 *     POST /chat/conversations/{id}/messages → `Message`). If the backend rebinds
 *     one of these, the tool's type follows automatically.
 *
 *  2. Named component re-exports (`Listing`, `Conversation`) for endpoints whose
 *     RESPONSE the spec leaves as a bare `object` (the controller declares no
 *     `@ApiResponse({ type })`, so openapi-typescript emits `Record<string,
 *     never>`). The ENTITY schema still exists in `components.schemas`, so the
 *     tools use it as the element type instead of an untyped
 *     `Record<string, unknown>`. This is the "narrow local type derived from a
 *     generated component" the ticket calls for.
 *
 * ── Contract gaps surfaced by this work (backend routes the MCP consumes that
 *    declare NO typed response schema — every field the tool reads off them is
 *    spec-uncovered; worth a backend `@ApiResponse` follow-up) ──
 *   - GET /rentals, /rentals/search/vibe, /rentals/{id}/similar  (result envelope
 *     `{ success?, data: Listing[] }` is untyped)
 *   - GET /rentals/{id}/availability          (`{ isAvailable, conflicts? }`)
 *   - GET /rentals/pricing-stats              (see `PricingStatsResponse` in pricing.ts)
 *   - PUT /bookings/{id}/status               (returns the updated booking as a bare object)
 *   - GET/POST /packages*                     (experiences have NO entity schema at all)
 *   - POST /ai/*                              (only the REQUEST DTOs are typed; responses are bare objects)
 *   Where a tool must read fields off one of these, it models exactly that
 *   envelope with a narrow local type carrying a `// contract gap` note, layered
 *   over a generated entity where one exists.
 */
import type { paths, components } from '@/generated/api-types.gen';

/* ── Generated entity schemas (element types for the tool layer) ──────────────── */
export type Listing = components['schemas']['Listing'];
export type Booking = components['schemas']['Booking'];
export type BookingResponseDto = components['schemas']['BookingResponseDto'];
export type Message = components['schemas']['Message'];
export type Conversation = components['schemas']['Conversation'];

/**
 * The `application/json` body a path's method binds for a given 2xx status,
 * inferred straight from the generated `paths` — or `never` when the spec
 * declares no such body.
 */
type JsonBody<Op, Status extends number> = Op extends {
  responses: { [S in Status]: { content: { 'application/json': infer B } } };
}
  ? B
  : never;

/** The typed 200 GET body a spec path declares (mirrors FE `apiClient` GetJson). */
export type GetResponse<P extends keyof paths> = paths[P] extends { get: infer Op }
  ? JsonBody<Op, 200>
  : never;

/** The typed 201 POST body a spec path declares. */
export type PostResponse<P extends keyof paths> = paths[P] extends { post: infer Op }
  ? JsonBody<Op, 201>
  : never;
